name: Push Stage Workflow VPS
on:
  workflow_call:
    inputs: 
      api-path:
        required: true
        type: string
jobs:
  deploy-to-server:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Api Path
          run: |
            cd ${{ inputs.api-path }}
            ls
            dotnet restore
            dotnet publish -c Release -o build
            ls
            echo ${{ vars.MICRO_SERVER_HOST }}
            echo ${{ vars.MICRO_SERVER_USER }}
            echo ${{ secrets.MICRO_SERVER_PASSWORD }}
        - run: ls
        - name: Create Directory
          uses: appleboy/ssh-action@master
          env:
            REPO_NAME: ${{ github.repository }} 
          with:
            host: ${{ vars.MICRO_SERVER_HOST }}
            username: ${{ vars.MICRO_SERVER_USER }}
            password: ${{ secrets.MICRO_SERVER_PASSWORD }}
            port: 22
            script: |
             echo ${REPO_NAME}
             export APP_NAME=${REPO_NAME}
             export APP_PORT=${APP_PORT}
             cd backend/
             APP_NAME=${REPO_NAME} mkdir -p $APP_NAME
        - run: ls
        - name: Copy files to server
          uses: appleboy/scp-action@master
          env:
            REPO_NAME: ${{ github.repository }}           
          with:
            host: ${{ vars.MICRO_SERVER_HOST }}
            username: ${{ vars.MICRO_SERVER_USER }}
            password: ${{ secrets.MICRO_SERVER_PASSWORD }}
            port: 22
            source: "build/*"
            target: "/root/backend/${REPO_NAME##*/}/"

        - name: Execute PM2 start
          uses: appleboy/ssh-action@master
          env:
            REPO_NAME: ${{ github.repository }} 
            APP_PORT: ${{ secrets.APP_PORT }}
          with:
            host: ${{ vars.MICRO_SERVER_HOST }}
            username: ${{ vars.MICRO_SERVER_USER }}
            password: ${{ secrets.MICRO_SERVER_PASSWORD }}
            port: 22
            script: |
             export APP_NAME=${REPO_NAME}
             export APP_PORT=${APP_PORT}
             pm2 startOrRestart /root/backend/${REPO_NAME##*/}/config/backend.config.js
