name: Push Stage Workflow VPS
on:
  workflow_call:
jobs:
  deploy-to-server:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        # Paso opcional: Compilar el proyecto, si es necesario
        - name: directory
          run: ls
        - name: dotnet restore
          run: dotnet restore
        - name: dotnet publish 
          run: dotnet publish -c Release -o build
        - run: ls

        - name: Copy files to server
          uses: appleboy/scp-action@master
          env:
            REPO_NAME: ${{ github.repository }}           
          with:
            host: ${{ secrets.MICRO_SERVER_HOST }}
            username: ${{ secrets.MICRO_SERVER_USER }}
            password: ${{ secrets.MICRO_SERVER_PASSWORD }}
            port: 22
            source: "build/*"
            target: "/root/backend/${REPO_NAME##*/}/"

        - name: Execute PM2 start
          uses: appleboy/ssh-action@master
          env:
            REPO_NAME: ${{ github.repository }} 
            APP_PORT: ${{ secrets.APP_PORT }}
          with:
            host: ${{ secrets.MICRO_SERVER_HOST }}
            username: ${{ secrets.MICRO_SERVER_USER }}
            password: ${{ secrets.MICRO_SERVER_PASSWORD }}
            port: 22
            script: |
             export APP_NAME=${REPO_NAME}
             export APP_PORT=${APP_PORT}
             pm2 startOrRestart /root/backend/${REPO_NAME##*/}/config/backend.config.js
